#!/bin/sh

PATH=/opt/bin:/opt/sbin:/sbin:/bin:/usr/sbin:/usr/bin

PIDFILE="/opt/var/run/mysqld.pid"
MYSQLD="/opt/bin/mysqld"

DB_DIR=/tmp/db		# put innodb and sync pointers in this dir
DB_TGZ=/opt/.db.tgz	# mysqldump backup

mysql_status ()
{
	[ -f $PIDFILE ] && [ -d /proc/`cat $PIDFILE` ]
}

start()
{
	# load ibdata to ramdisk
	rm -rf $DB_DIR
	mkdir -p $DB_DIR/mysql
	[ -f $DB_TGZ ] && {	# normal shutdown
		tar xzf $DB_TGZ -C /
	} || {	# power lost, restore from mysqldump or re-create db
		echo 'TODO: restore from sql'
	}

	$MYSQLD --pid-file=$PIDFILE &
}

stop()
{
	echo -n "shutting down mysql"
	kill `cat $PIDFILE` > /dev/null 2>&1
	while pidof mysqld >/dev/null; do
		echo -n .
		sleep 1
	done
	tar czf $DB_TGZ $DB_DIR
	sync
	echo ' done'
}

case "$1" in
	start)
		if mysql_status
		then
			echo mysqld is already running
		else
			start
		fi
		;;
	stop)
		if mysql_status
		then
			stop
		else
			echo mysqld is not running
		fi
		;;
	status)
		if mysql_status
		then
			echo mysqld is already running
		else
			echo mysqld is not running
		fi
		;;

	restart)
		stop
		sleep 3
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		;;
esac
